version: "3"
services:
  client:
    stdin_open: true
    build: ./
    image: garybagn/portfolio
    expose:
      - 3000
    ports:
      - 80:3000
    volumes:
      - ./:/app/
    environment:
      CHOKIDAR_USEPOLLING: "true"
